const mongoose = require("mongoose");
let Schema = mongoose.Schema;

let auctionSchema = new Schema({
    // The primary key "AuctionId" is the _id auto generated by the MongoDB
    productId: {
        type: String,
        required: true
    },
    auctCategoryId: {
        type: String,
        required: true
    },  
    startDate: {
        type: Date,
        default: Date()
    },  
    endDate: {
        type: Date,
        default: Date()
    },  
    price: Number,  
    title: {
        type: String,
        required: true
    },
    description: String 
});
const auctionMODEL = mongoose.model('auctions', auctionSchema)

module.exports = auctionMODEL;