const mongoose = require("mongoose");
let Schema = mongoose.Schema;

let auctionSchema = new Schema({
    // The primary key "AuctionId" is the _id auto generated by the MongoDB
    product: {
        name: String,
        description: String
    },
    auctCategory: {
        type: String,
        required: true
    },  
    startDate: {
        type: Date,
        default: Date()
    },  
    endDate: {
        type: Date,
        default: Date()
    },  
    title: {
        type: String,
        required: true
    },
    problemList: [{
        userFirstName: String,
        userLastName: String,
        userEmailAddress: String,
        problemDescription: String,
        reportDate: Date
    }], 
    userList: [{
        userName: String,
        emailAddress: String
    }],
    status: String,
    description: String,
    price: Number
});
const auctionMODEL = mongoose.model('auctions', auctionSchema)

module.exports = auctionMODEL;