const mongoose = require("mongoose");
let Schema = mongoose.Schema;

let auctionSchema = new Schema({
    // The primary key "AuctionId" is the _id auto generated by the MongoDB
    auctionTypeId: {
        type: String,
        required: true
    },
    productId: {
        type: String,
        required: true
    },
    auctCategoryId: {
        type: String,
        required: true
    },  
    StartDate: Date,  
    EndDate: Date,  
    Price: Number,  
    Title: {
        type: String,
        required: true
    },
    Description: String 
});

module.exports = auctionSchema;