const mongoose = require("mongoose");
let Schema = mongoose.Schema;

let bidhistorySchema = new Schema({
    // The primary key "BidHistId" is the _id auto generated by the MongoDB
    userID: {
        type: String,
        required: true
    },
    auctionID: {
        type: Number,
        required: true
    },
    bidPrice: Number
});

module.exports = bidhistorySchema;